  version: '3.8'
  services:
    db:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=clojure_bot_telegram
      ports:
        - 3306:3306
      volumes:
        - "./db:/docker-entrypoint-initdb.d"
    bot:
      build: .
      links:
        - db
      depends_on:
        - db